### ISSUE TITLE
Hey -- from Mellowtel (high internet consumption fixed)

### ISSUE THREAD

**Issue by mellowtel** [TheLifeIsYours/mc-app#1]
## Summary

Hey @TheLifeIsYours,

It's Arslan from Mellowtel.dev. Sorry for the unorthodox communication channel, I couldn't find any other way to reach out.
Unfortunately, it seems like you had a bad experience with our [open-source library](https://github.com/mellowtel-inc/mellowtel-js) for browser plugins.
Just wanted to point out a couple of things in the hope of clarifying.

There was an issue in the recently published version imported by JiffyReader that ran the speed test on every tab load, consuming a lot of bandwidth. This issue has been fixed and a PR is pending to be merged and published.
Also, the library shouldn't activate by default without users explicitly agreeing. It looks like unfortunately there was a bug in the update page that made it so, but it has also been fixed in the recent PR. You can check for yourself here: https://github.com/ansh/jiffyreader.com/issues/298

 Users can always opt out from the extension popup.

We're trying to create a safe and sustainable ecosystem for browser plugin developers to make a living thanks to their work without compromising their users' privacy or experience. In this way, developers can focus on creating great products that benefit all users and improve the browsing experience and the browsers on which they are.

We are trying to see if the concept can work and any feedback is welcome. 

Sorry for the issues it has caused to you and let me know if I can help in any way.

Thanks,
Arslan

**Comment by TheLifeIsYours** [comment]
As a developer myself, adding a piece of software to create a botnet that
uses bandwidth and cpu capacity that have nothing to do with the original
functions of the program is scummy. You take your existing userbase and
twist it around for monetization. This is in my opinion wrong and
unethical. Your software is an accessibility tool, it changes font size,
spacing and boldness. That's all it should ever do! You want to create a
botnet for AI learning? Then create a separate extension that does just
that, don't jam it inside a tool that sits idle on your existing users
devices. Do what other OSS does, make a koffee or ask kindly for donations.
You won't get any more feedback from me than that.

**Comment by mellowtel** [comment]
Hey, I totally get your point. Thanks for taking the time to reply.

The core idea is that users are opted out by default and can opt in if they want to support. There was a bug that opted-in when people closed the update page and that has been corrected now (you can check it too since it's open source). 

The problem I noticed with donations for browser extensions is that the vast majority of people are not willing to pay or donate and developers have no way to sustain themselves and usually have to sell their extensions to companies that then collect and sell users' data or fill them up with ads/affiliate links.

With this concept, we want to explore if people are instead willing to share a small portion of their bandwidth if they want to, and it won't use much of their bandwidth (again in this version unfortunately there was a bug that has been fixed). So it does not collect any kind of personal data.

So the idea is if users want to sustain the developer but are not willing to donate or don't have the means to do it they can opt-in and it will only use enough bandwidth that is required to keep one additional incognito tab open for a few minutes a day.

If they are not willing to do it they can decide to not opt-in (or opt-out at any moment) and keep using the service for free as they have always done.

Again I'm sorry for the bugs and the bad user experience. Hope this clarifies it but I totally understand if you don't like the concept. Thanks for your time.
